"""Add species and plants

Revision ID: 2718d45a1228
Revises: 8b523f53c857
Create Date: 2026-09-04 12:19:11.033262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2718d45a1228"
down_revision: str | Sequence[str] | None = "8b523f53c857"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "species",
        sa.Column("scientific_name", sa.String(length=200), nullable=False),
        sa.Column("primary_common_name", sa.String(length=200), nullable=True),
        sa.Column("family_name", sa.String(length=100), nullable=True),
        sa.Column("genus_name", sa.String(length=100), nullable=True),
        sa.Column("is_hybrid", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_source", sa.String(length=200), nullable=True),
        sa.Column("reference_url", sa.String(length=500), nullable=True),
        sa.Column("human_verified", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_species")),
        sa.UniqueConstraint("scientific_name", name="species_scientific_name"),
    )
    with op.batch_alter_table("species", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_species_scientific_name"), ["scientific_name"], unique=False
        )

    op.create_table(
        "plants",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("species_id", sa.Uuid(), nullable=True),
        sa.Column("parent_plant_id", sa.Uuid(), nullable=True),
        sa.Column("plant_code", sa.String(length=30), nullable=False),
        sa.Column("nickname", sa.String(length=100), nullable=True),
        sa.Column("cultivar_name", sa.String(length=150), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DORMANT",
                "QUARANTINED",
                "DECEASED",
                "TRANSFERRED",
                "UNKNOWN",
                name="plant_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "identification_status",
            sa.Enum(
                "UNCONFIRMED",
                "AI_SUGGESTED",
                "USER_CONFIRMED",
                "EXPERT_CONFIRMED",
                name="plant_identification_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "identification_confidence", sa.Numeric(precision=5, scale=4), nullable=True
        ),
        sa.Column("acquired_on", sa.Date(), nullable=True),
        sa.Column("acquisition_source", sa.String(length=200), nullable=True),
        sa.Column("deceased_on", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "deceased_on IS NULL OR acquired_on IS NULL OR deceased_on >= acquired_on",
            name=op.f("ck_plants_plant_deceased_after_acquired"),
        ),
        sa.CheckConstraint(
            "identification_confidence IS NULL OR (identification_confidence >= 0 AND identification_confidence <= 1)",
            name=op.f("ck_plants_plant_identification_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_plants_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_plant_id"],
            ["plants.id"],
            name=op.f("fk_plants_parent_plant_id_plants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["species_id"],
            ["species.id"],
            name=op.f("fk_plants_species_id_species"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plants")),
        sa.UniqueConstraint(
            "household_id", "plant_code", name="plant_code_per_household"
        ),
    )
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plants_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plants_parent_plant_id"), ["parent_plant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plants_species_id"), ["species_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plants_species_id"))
        batch_op.drop_index(batch_op.f("ix_plants_parent_plant_id"))
        batch_op.drop_index(batch_op.f("ix_plants_household_id"))

    op.drop_table("plants")
    with op.batch_alter_table("species", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_species_scientific_name"))

    op.drop_table("species")
    # ### end Alembic commands ###
