"""Add substrate mixtures and history

Revision ID: 3942a8e984d8
Revises: 756d82bba12b
Create Date: 2026-09-04 14:06:07.275687

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3942a8e984d8"
down_revision: str | Sequence[str] | None = "756d82bba12b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "substrate_components",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "ORGANIC",
                "MINERAL",
                "INERT",
                "LIVING",
                "SYNTHETIC",
                "OTHER",
                name="substrate_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reference_source", sa.String(length=200), nullable=True),
        sa.Column("reference_url", sa.String(length=500), nullable=True),
        sa.Column("human_verified", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_substrate_components")),
        sa.UniqueConstraint("name", name="substrate_component_name"),
    )
    with op.batch_alter_table("substrate_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_substrate_components_name"), ["name"], unique=False
        )

    op.create_table(
        "substrate_mixes",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("mix_code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_substrate_mixes_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_substrate_mixes")),
        sa.UniqueConstraint(
            "household_id", "mix_code", name="substrate_mix_code_per_household"
        ),
    )
    with op.batch_alter_table("substrate_mixes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_substrate_mixes_household_id"),
            ["household_id"],
            unique=False,
        )

    op.create_table(
        "plant_substrate_history",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("mix_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name=op.f("ck_plant_substrate_history_plant_substrate_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["mix_id"],
            ["substrate_mixes.id"],
            name=op.f("fk_plant_substrate_history_mix_id_substrate_mixes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_substrate_history_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_substrate_history")),
        sa.UniqueConstraint(
            "plant_id", "started_at", name="plant_substrate_start_per_plant"
        ),
    )
    with op.batch_alter_table("plant_substrate_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_substrate_history_mix_id"), ["mix_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plant_substrate_history_plant_id"),
            ["plant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_substrate_history_started_at"),
            ["started_at"],
            unique=False,
        )

    op.create_table(
        "substrate_mix_components",
        sa.Column("mix_id", sa.Uuid(), nullable=False),
        sa.Column("component_id", sa.Uuid(), nullable=False),
        sa.Column("proportion_parts", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "proportion_parts > 0",
            name=op.f("ck_substrate_mix_components_substrate_component_parts_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["component_id"],
            ["substrate_components.id"],
            name=op.f("fk_substrate_mix_components_component_id_substrate_components"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["mix_id"],
            ["substrate_mixes.id"],
            name=op.f("fk_substrate_mix_components_mix_id_substrate_mixes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_substrate_mix_components")),
        sa.UniqueConstraint(
            "mix_id", "component_id", name="substrate_component_per_mix"
        ),
    )
    with op.batch_alter_table("substrate_mix_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_substrate_mix_components_component_id"),
            ["component_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_substrate_mix_components_mix_id"), ["mix_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("substrate_mix_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_substrate_mix_components_mix_id"))
        batch_op.drop_index(batch_op.f("ix_substrate_mix_components_component_id"))

    op.drop_table("substrate_mix_components")
    with op.batch_alter_table("plant_substrate_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_substrate_history_started_at"))
        batch_op.drop_index(batch_op.f("ix_plant_substrate_history_plant_id"))
        batch_op.drop_index(batch_op.f("ix_plant_substrate_history_mix_id"))

    op.drop_table("plant_substrate_history")
    with op.batch_alter_table("substrate_mixes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_substrate_mixes_household_id"))

    op.drop_table("substrate_mixes")
    with op.batch_alter_table("substrate_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_substrate_components_name"))

    op.drop_table("substrate_components")
    # ### end Alembic commands ###
