"""Add weather snapshots

Revision ID: 55d02bcd9026
Revises: 66a441b1bdc8
Create Date: 2026-09-04 16:45:41.151944

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d02bcd9026"
down_revision: str | Sequence[str] | None = "66a441b1bdc8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_snapshots",
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "record_type",
            sa.Enum(
                "OBSERVED",
                "FORECAST",
                "HISTORICAL",
                name="weather_record_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("provider_weather_code", sa.String(length=50), nullable=True),
        sa.Column(
            "condition",
            sa.Enum(
                "CLEAR",
                "MOSTLY_CLEAR",
                "PARTLY_CLOUDY",
                "OVERCAST",
                "FOG",
                "DRIZZLE",
                "RAIN",
                "FREEZING_RAIN",
                "SNOW",
                "THUNDERSTORM",
                "UNKNOWN",
                name="weather_condition",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_daylight", sa.Boolean(), nullable=True),
        sa.Column("temperature_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "apparent_temperature_c", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column(
            "relative_humidity_pct", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("cloud_cover_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "precipitation_probability_pct",
            sa.Numeric(precision=5, scale=2),
            nullable=True,
        ),
        sa.Column("precipitation_mm", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("wind_speed_kph", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("wind_direction_degrees", sa.Integer(), nullable=True),
        sa.Column(
            "surface_pressure_hpa", sa.Numeric(precision=7, scale=2), nullable=True
        ),
        sa.Column(
            "solar_radiation_w_m2", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("uv_index", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cloud_cover_pct IS NULL OR cloud_cover_pct BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_valid_weather_cloud_cover"),
        ),
        sa.CheckConstraint(
            "precipitation_mm IS NULL OR precipitation_mm >= 0",
            name=op.f("ck_weather_snapshots_valid_weather_precipitation"),
        ),
        sa.CheckConstraint(
            "precipitation_probability_pct IS NULL OR precipitation_probability_pct BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_valid_precipitation_probability"),
        ),
        sa.CheckConstraint(
            "relative_humidity_pct IS NULL OR relative_humidity_pct BETWEEN 0 AND 100",
            name=op.f("ck_weather_snapshots_valid_weather_humidity"),
        ),
        sa.CheckConstraint(
            "solar_radiation_w_m2 IS NULL OR solar_radiation_w_m2 >= 0",
            name=op.f("ck_weather_snapshots_valid_solar_radiation"),
        ),
        sa.CheckConstraint(
            "uv_index IS NULL OR uv_index >= 0",
            name=op.f("ck_weather_snapshots_valid_weather_uv_index"),
        ),
        sa.CheckConstraint(
            "wind_direction_degrees IS NULL OR wind_direction_degrees BETWEEN 0 AND 359",
            name=op.f("ck_weather_snapshots_valid_weather_wind_direction"),
        ),
        sa.CheckConstraint(
            "wind_speed_kph IS NULL OR wind_speed_kph >= 0",
            name=op.f("ck_weather_snapshots_valid_weather_wind_speed"),
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_weather_snapshots_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weather_snapshots")),
    )
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_weather_snapshots_measured_at"),
            ["measured_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_weather_snapshots_site_id"), ["site_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("weather_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_weather_snapshots_site_id"))
        batch_op.drop_index(batch_op.f("ix_weather_snapshots_measured_at"))

    op.drop_table("weather_snapshots")
    # ### end Alembic commands ###
