"""Add observations care and health tracking

Revision ID: 5c16714ec5bb
Revises: 3942a8e984d8
Create Date: 2026-09-04 14:53:25.754460

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5c16714ec5bb"
down_revision: str | Sequence[str] | None = "3942a8e984d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "care_events",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("performed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "WATERING",
                "WATER_CHANGE",
                "WATER_TOP_OFF",
                "FERTILIZING",
                "REPOTTING",
                "PRUNING",
                "CLEANING",
                "ROTATING",
                "PEST_TREATMENT",
                "PROPAGATION",
                "OTHER",
                name="care_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "NLP_ASSISTANT",
                "AUTOMATED",
                "IMPORTED",
                name="care_event_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount_ml", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("fertilizer_name", sa.String(length=200), nullable=True),
        sa.Column(
            "fertilizer_dilution_ratio", sa.Numeric(precision=8, scale=2), nullable=True
        ),
        sa.Column("water_ph", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("water_ec_ms_cm", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("product_name", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "amount_ml IS NULL OR amount_ml >= 0",
            name=op.f("ck_care_events_valid_care_amount"),
        ),
        sa.CheckConstraint(
            "fertilizer_dilution_ratio IS NULL OR fertilizer_dilution_ratio > 0",
            name=op.f("ck_care_events_valid_fertilizer_dilution"),
        ),
        sa.CheckConstraint(
            "water_ec_ms_cm IS NULL OR water_ec_ms_cm >= 0",
            name=op.f("ck_care_events_valid_water_ec"),
        ),
        sa.CheckConstraint(
            "water_ph IS NULL OR water_ph BETWEEN 0 AND 14",
            name=op.f("ck_care_events_valid_water_ph"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
            name=op.f("fk_care_events_performed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_care_events_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_care_events")),
    )
    with op.batch_alter_table("care_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_care_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_care_events_performed_by_user_id"),
            ["performed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_care_events_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "health_issues",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("detected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "PEST",
                "DISEASE",
                "ROOT_PROBLEM",
                "NUTRIENT_PROBLEM",
                "WATERING_PROBLEM",
                "LIGHT_PROBLEM",
                "TEMPERATURE_PROBLEM",
                "HUMIDITY_PROBLEM",
                "PHYSICAL_DAMAGE",
                "UNKNOWN",
                "OTHER",
                name="health_issue_category",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "SUSPECTED",
                "CONFIRMED",
                "MONITORING",
                "TREATING",
                "RESOLVED",
                "CHRONIC",
                name="health_issue_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "PHOTO_AI",
                "SENSOR",
                "DERIVED",
                "IMPORTED",
                name="health_issue_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("severity_score", sa.Integer(), nullable=True),
        sa.Column("affected_area", sa.String(length=200), nullable=True),
        sa.Column("suspected_cause", sa.Text(), nullable=True),
        sa.Column("diagnosis", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("human_verified", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_health_issues_valid_health_issue_confidence"),
        ),
        sa.CheckConstraint(
            "resolved_at IS NULL OR resolved_at >= detected_at",
            name=op.f("ck_health_issues_valid_health_issue_dates"),
        ),
        sa.CheckConstraint(
            "severity_score IS NULL OR severity_score BETWEEN 1 AND 5",
            name=op.f("ck_health_issues_valid_health_issue_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["detected_by_user_id"],
            ["users.id"],
            name=op.f("fk_health_issues_detected_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_health_issues_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_issues")),
    )
    with op.batch_alter_table("health_issues", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_health_issues_detected_at"), ["detected_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_health_issues_detected_by_user_id"),
            ["detected_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_health_issues_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "plant_observations",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "observation_type",
            sa.Enum(
                "ROUTINE_CHECK",
                "HEALTH_CHECK",
                "PHOTO_ASSESSMENT",
                "SENSOR_READING",
                "FOLLOW_UP",
                "OTHER",
                name="observation_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "PHOTO_AI",
                "SENSOR",
                "DERIVED",
                "IMPORTED",
                name="observation_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_detail", sa.String(length=200), nullable=True),
        sa.Column(
            "overall_health_score", sa.Numeric(precision=4, scale=2), nullable=True
        ),
        sa.Column("leaf_count", sa.Integer(), nullable=True),
        sa.Column("new_leaf_count", sa.Integer(), nullable=True),
        sa.Column("yellow_leaf_count", sa.Integer(), nullable=True),
        sa.Column("damaged_leaf_count", sa.Integer(), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("canopy_width_cm", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("visible_pests", sa.Boolean(), nullable=True),
        sa.Column("flowering", sa.Boolean(), nullable=True),
        sa.Column("summary", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("human_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "canopy_width_cm IS NULL OR canopy_width_cm >= 0",
            name=op.f("ck_plant_observations_valid_canopy_width"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_plant_observations_valid_observation_confidence"),
        ),
        sa.CheckConstraint(
            "damaged_leaf_count IS NULL OR damaged_leaf_count >= 0",
            name=op.f("ck_plant_observations_valid_damaged_leaf_count"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm >= 0",
            name=op.f("ck_plant_observations_valid_plant_height"),
        ),
        sa.CheckConstraint(
            "leaf_count IS NULL OR leaf_count >= 0",
            name=op.f("ck_plant_observations_valid_leaf_count"),
        ),
        sa.CheckConstraint(
            "new_leaf_count IS NULL OR new_leaf_count >= 0",
            name=op.f("ck_plant_observations_valid_new_leaf_count"),
        ),
        sa.CheckConstraint(
            "overall_health_score IS NULL OR overall_health_score BETWEEN 0 AND 10",
            name=op.f("ck_plant_observations_valid_overall_health_score"),
        ),
        sa.CheckConstraint(
            "yellow_leaf_count IS NULL OR yellow_leaf_count >= 0",
            name=op.f("ck_plant_observations_valid_yellow_leaf_count"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_observations_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_observations")),
    )
    with op.batch_alter_table("plant_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_observations_observed_at"),
            ["observed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_observations_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "treatments",
        sa.Column("health_issue_id", sa.Uuid(), nullable=False),
        sa.Column("performed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("treatment_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "IN_PROGRESS",
                "COMPLETED",
                "STOPPED",
                "CANCELLED",
                name="treatment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("product_name", sa.String(length=200), nullable=True),
        sa.Column("application_method", sa.String(length=200), nullable=True),
        sa.Column("dosage_description", sa.String(length=300), nullable=True),
        sa.Column("frequency_description", sa.String(length=300), nullable=True),
        sa.Column(
            "outcome",
            sa.Enum(
                "NOT_ASSESSED",
                "NO_CHANGE",
                "IMPROVED",
                "RESOLVED",
                "WORSENED",
                "ADVERSE_REACTION",
                name="treatment_outcome",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("outcome_assessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("outcome_notes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_treatments_valid_treatment_dates"),
        ),
        sa.CheckConstraint(
            "outcome_assessed_at IS NULL OR outcome_assessed_at >= started_at",
            name=op.f("ck_treatments_valid_treatment_outcome_date"),
        ),
        sa.ForeignKeyConstraint(
            ["health_issue_id"],
            ["health_issues.id"],
            name=op.f("fk_treatments_health_issue_id_health_issues"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["performed_by_user_id"],
            ["users.id"],
            name=op.f("fk_treatments_performed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_treatments")),
    )
    with op.batch_alter_table("treatments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_treatments_health_issue_id"),
            ["health_issue_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_treatments_performed_by_user_id"),
            ["performed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_treatments_started_at"), ["started_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("treatments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_treatments_started_at"))
        batch_op.drop_index(batch_op.f("ix_treatments_performed_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_treatments_health_issue_id"))

    op.drop_table("treatments")
    with op.batch_alter_table("plant_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_observations_plant_id"))
        batch_op.drop_index(batch_op.f("ix_plant_observations_observed_at"))

    op.drop_table("plant_observations")
    with op.batch_alter_table("health_issues", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_issues_plant_id"))
        batch_op.drop_index(batch_op.f("ix_health_issues_detected_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_health_issues_detected_at"))

    op.drop_table("health_issues")
    with op.batch_alter_table("care_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_care_events_plant_id"))
        batch_op.drop_index(batch_op.f("ix_care_events_performed_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_care_events_occurred_at"))

    op.drop_table("care_events")
    # ### end Alembic commands ###
