"""Add tasks recommendations and outcomes

Revision ID: 66a441b1bdc8
Revises: 5c16714ec5bb
Create Date: 2026-09-04 16:03:33.897337

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66a441b1bdc8"
down_revision: str | Sequence[str] | None = "5c16714ec5bb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendations",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("health_issue_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "recommendation_type",
            sa.Enum(
                "WATER_ADJUSTMENT",
                "MOVE_TO_DIFFERENT_LIGHT",
                "ADJUST_GROW_LIGHT",
                "REPOT",
                "CHANGE_SUBSTRATE",
                "CHANGE_CULTIVATION_METHOD",
                "FERTILIZE",
                "TREAT_HEALTH_ISSUE",
                "ADJUST_HUMIDITY",
                "MONITOR",
                "KEEP_AS_IS",
                "OTHER",
                name="recommendation_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PROPOSED",
                "ACCEPTED",
                "DECLINED",
                "COMPLETED",
                "EXPIRED",
                "SUPERSEDED",
                name="recommendation_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "RULE_ENGINE",
                "ML_MODEL",
                "AI_ASSISTANT",
                "HUMAN_EXPERT",
                "MANUAL",
                "IMPORTED",
                name="recommendation_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("action_description", sa.Text(), nullable=False),
        sa.Column("expected_outcome", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("model_name", sa.String(length=200), nullable=True),
        sa.Column("model_version", sa.String(length=100), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "accepted_at IS NULL OR accepted_at >= generated_at",
            name=op.f("ck_recommendations_valid_recommendation_acceptance_date"),
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= generated_at",
            name=op.f("ck_recommendations_valid_recommendation_completion_date"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_recommendations_valid_recommendation_confidence"),
        ),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until >= generated_at",
            name=op.f("ck_recommendations_valid_recommendation_expiration"),
        ),
        sa.ForeignKeyConstraint(
            ["health_issue_id"],
            ["health_issues.id"],
            name=op.f("fk_recommendations_health_issue_id_health_issues"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_recommendations_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_recommendations_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
    )
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendations_generated_at"),
            ["generated_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_health_issue_id"),
            ["health_issue_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_household_id"),
            ["household_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendations_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "tasks",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("plant_id", sa.Uuid(), nullable=True),
        sa.Column("health_issue_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "task_type",
            sa.Enum(
                "WATER",
                "CHANGE_WATER",
                "TOP_OFF_WATER",
                "INSPECT",
                "TREAT",
                "MOVE",
                "REPOT",
                "FERTILIZE",
                "PRUNE",
                "CLEAN",
                "ROTATE",
                "PHOTOGRAPH",
                "MEASURE",
                "OTHER",
                name="task_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "SKIPPED",
                "CANCELLED",
                name="task_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum(
                "LOW",
                "MEDIUM",
                "HIGH",
                "URGENT",
                name="task_priority",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL",
                "RECOMMENDATION",
                "RULE_ENGINE",
                "NLP_ASSISTANT",
                "SYSTEM",
                "IMPORTED",
                name="task_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("repeat_interval_days", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= created_at",
            name=op.f("ck_tasks_valid_task_completion_date"),
        ),
        sa.CheckConstraint(
            "repeat_interval_days IS NULL OR repeat_interval_days > 0",
            name=op.f("ck_tasks_valid_task_repeat_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_tasks_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["health_issue_id"],
            ["health_issues.id"],
            name=op.f("fk_tasks_health_issue_id_health_issues"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_tasks_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_tasks_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_tasks_assigned_to_user_id"),
            ["assigned_to_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_created_by_user_id"),
            ["created_by_user_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_tasks_due_at"), ["due_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_tasks_health_issue_id"), ["health_issue_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_household_id"), ["household_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_tasks_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "recommendation_outcomes",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("assessed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("baseline_observation_id", sa.Uuid(), nullable=True),
        sa.Column("follow_up_observation_id", sa.Uuid(), nullable=True),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "result",
            sa.Enum(
                "NOT_ASSESSED",
                "IMPROVED",
                "NO_CHANGE",
                "WORSENED",
                "MIXED",
                name="recommendation_result",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "health_score_before", sa.Numeric(precision=4, scale=2), nullable=True
        ),
        sa.Column(
            "health_score_after", sa.Numeric(precision=4, scale=2), nullable=True
        ),
        sa.Column("follow_up_days", sa.Integer(), nullable=True),
        sa.Column("observed_changes", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "baseline_observation_id IS NULL OR follow_up_observation_id IS NULL OR baseline_observation_id != follow_up_observation_id",
            name=op.f("ck_recommendation_outcomes_different_outcome_observations"),
        ),
        sa.CheckConstraint(
            "follow_up_days IS NULL OR follow_up_days >= 0",
            name=op.f("ck_recommendation_outcomes_valid_outcome_follow_up_days"),
        ),
        sa.CheckConstraint(
            "health_score_after IS NULL OR health_score_after BETWEEN 0 AND 10",
            name=op.f("ck_recommendation_outcomes_valid_outcome_health_score_after"),
        ),
        sa.CheckConstraint(
            "health_score_before IS NULL OR health_score_before BETWEEN 0 AND 10",
            name=op.f("ck_recommendation_outcomes_valid_outcome_health_score_before"),
        ),
        sa.ForeignKeyConstraint(
            ["assessed_by_user_id"],
            ["users.id"],
            name=op.f("fk_recommendation_outcomes_assessed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["baseline_observation_id"],
            ["plant_observations.id"],
            name=op.f(
                "fk_recommendation_outcomes_baseline_observation_id_plant_observations"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["follow_up_observation_id"],
            ["plant_observations.id"],
            name=op.f(
                "fk_recommendation_outcomes_follow_up_observation_id_plant_observations"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.id"],
            name=op.f("fk_recommendation_outcomes_recommendation_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_outcomes")),
    )
    with op.batch_alter_table("recommendation_outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_outcomes_assessed_at"),
            ["assessed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_outcomes_assessed_by_user_id"),
            ["assessed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_outcomes_baseline_observation_id"),
            ["baseline_observation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_outcomes_follow_up_observation_id"),
            ["follow_up_observation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_outcomes_recommendation_id"),
            ["recommendation_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_outcomes_recommendation_id"))
        batch_op.drop_index(
            batch_op.f("ix_recommendation_outcomes_follow_up_observation_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_recommendation_outcomes_baseline_observation_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_recommendation_outcomes_assessed_by_user_id")
        )
        batch_op.drop_index(batch_op.f("ix_recommendation_outcomes_assessed_at"))

    op.drop_table("recommendation_outcomes")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_plant_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_household_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_health_issue_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_due_at"))
        batch_op.drop_index(batch_op.f("ix_tasks_created_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_tasks_assigned_to_user_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendations_plant_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_household_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_health_issue_id"))
        batch_op.drop_index(batch_op.f("ix_recommendations_generated_at"))

    op.drop_table("recommendations")
    # ### end Alembic commands ###
