"""Add environmental measurements

Revision ID: 6e30bf62a109
Revises: 55d02bcd9026
Create Date: 2026-09-04 17:18:03.137166

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e30bf62a109"
down_revision: str | Sequence[str] | None = "55d02bcd9026"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "environmental_measurements",
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("plant_id", sa.Uuid(), nullable=True),
        sa.Column("light_source_id", sa.Uuid(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "MANUAL_METER",
                "PHONE_SENSOR",
                "PHYSICAL_SENSOR",
                "IMPORTED",
                "DERIVED",
                name="measurement_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "light_context",
            sa.Enum(
                "AMBIENT_ZONE",
                "PLANT_LEAF_LEVEL",
                "AT_LIGHT_SOURCE",
                "DIRECT_SUN",
                "GROW_LIGHT_ONLY",
                "MIXED_LIGHT",
                "UNKNOWN",
                name="light_measurement_context",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("device_name", sa.String(length=150), nullable=True),
        sa.Column("measurement_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("lux", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("ppfd_umol_m2_s", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("dli_mol_m2_day", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("temperature_c", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            "relative_humidity_pct", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column("soil_moisture_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "water_temperature_c", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("water_ph", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("water_ec_ms_cm", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_environmental_measurements_valid_measurement_confidence"),
        ),
        sa.CheckConstraint(
            "dli_mol_m2_day IS NULL OR dli_mol_m2_day >= 0",
            name=op.f("ck_environmental_measurements_valid_measurement_dli"),
        ),
        sa.CheckConstraint(
            "lux IS NOT NULL OR ppfd_umol_m2_s IS NOT NULL OR dli_mol_m2_day IS NOT NULL OR temperature_c IS NOT NULL OR relative_humidity_pct IS NOT NULL OR soil_moisture_pct IS NOT NULL OR water_temperature_c IS NOT NULL OR water_ph IS NOT NULL OR water_ec_ms_cm IS NOT NULL",
            name=op.f("ck_environmental_measurements_measurement_has_value"),
        ),
        sa.CheckConstraint(
            "lux IS NULL OR lux >= 0",
            name=op.f("ck_environmental_measurements_valid_measurement_lux"),
        ),
        sa.CheckConstraint(
            "measurement_duration_seconds IS NULL OR measurement_duration_seconds > 0",
            name=op.f("ck_environmental_measurements_valid_measurement_duration"),
        ),
        sa.CheckConstraint(
            "ppfd_umol_m2_s IS NULL OR ppfd_umol_m2_s >= 0",
            name=op.f("ck_environmental_measurements_valid_measurement_ppfd"),
        ),
        sa.CheckConstraint(
            "relative_humidity_pct IS NULL OR relative_humidity_pct BETWEEN 0 AND 100",
            name=op.f("ck_environmental_measurements_valid_measurement_humidity"),
        ),
        sa.CheckConstraint(
            "soil_moisture_pct IS NULL OR soil_moisture_pct BETWEEN 0 AND 100",
            name=op.f("ck_environmental_measurements_valid_measurement_soil_moisture"),
        ),
        sa.CheckConstraint(
            "water_ec_ms_cm IS NULL OR water_ec_ms_cm >= 0",
            name=op.f("ck_environmental_measurements_valid_measurement_water_ec"),
        ),
        sa.CheckConstraint(
            "water_ph IS NULL OR water_ph BETWEEN 0 AND 14",
            name=op.f("ck_environmental_measurements_valid_measurement_water_ph"),
        ),
        sa.ForeignKeyConstraint(
            ["light_source_id"],
            ["light_sources.id"],
            name=op.f("fk_environmental_measurements_light_source_id_light_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_environmental_measurements_plant_id_plants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_environmental_measurements_recorded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["environmental_zones.id"],
            name=op.f("fk_environmental_measurements_zone_id_environmental_zones"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environmental_measurements")),
    )
    with op.batch_alter_table("environmental_measurements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_environmental_measurements_light_source_id"),
            ["light_source_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environmental_measurements_measured_at"),
            ["measured_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environmental_measurements_plant_id"),
            ["plant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environmental_measurements_recorded_by_user_id"),
            ["recorded_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_environmental_measurements_zone_id"),
            ["zone_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("environmental_measurements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_environmental_measurements_zone_id"))
        batch_op.drop_index(
            batch_op.f("ix_environmental_measurements_recorded_by_user_id")
        )
        batch_op.drop_index(batch_op.f("ix_environmental_measurements_plant_id"))
        batch_op.drop_index(batch_op.f("ix_environmental_measurements_measured_at"))
        batch_op.drop_index(batch_op.f("ix_environmental_measurements_light_source_id"))

    op.drop_table("environmental_measurements")
    # ### end Alembic commands ###
