"""Add watering method to care events

Revision ID: 72ca08a46249
Revises: 6e30bf62a109
Create Date: 2026-09-10 12:38:38.549924

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72ca08a46249"
down_revision: str | Sequence[str] | None = "6e30bf62a109"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("care_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "watering_method",
                sa.Enum("TOP", "BOTTOM", name="watering_method", native_enum=False),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("care_events", schema=None) as batch_op:
        batch_op.drop_column("watering_method")

    # ### end Alembic commands ###
