"""Add containers and cultivation history

Revision ID: 756d82bba12b
Revises: a28eea245a64
Create Date: 2026-09-04 13:46:54.671265

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "756d82bba12b"
down_revision: str | Sequence[str] | None = "a28eea245a64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "containers",
        sa.Column("household_id", sa.Uuid(), nullable=False),
        sa.Column("container_code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=True),
        sa.Column(
            "container_type",
            sa.Enum(
                "NURSERY_POT",
                "STANDARD_POT",
                "CACHEPOT",
                "HANGING_BASKET",
                "SELF_WATERING_POT",
                "VASE",
                "JAR",
                "RESERVOIR",
                "NET_POT",
                "MOUNT",
                "OTHER",
                name="container_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "material",
            sa.Enum(
                "PLASTIC",
                "TERRACOTTA",
                "CERAMIC",
                "GLASS",
                "METAL",
                "WOOD",
                "FABRIC",
                "CONCRETE",
                "OTHER",
                "UNKNOWN",
                name="container_material",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("diameter_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("width_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("depth_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("height_cm", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("volume_l", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column("has_drainage", sa.Boolean(), nullable=True),
        sa.Column("is_self_watering", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "depth_cm IS NULL OR depth_cm > 0",
            name=op.f("ck_containers_container_depth_positive"),
        ),
        sa.CheckConstraint(
            "diameter_cm IS NULL OR diameter_cm > 0",
            name=op.f("ck_containers_container_diameter_positive"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm > 0",
            name=op.f("ck_containers_container_height_positive"),
        ),
        sa.CheckConstraint(
            "volume_l IS NULL OR volume_l > 0",
            name=op.f("ck_containers_container_volume_positive"),
        ),
        sa.CheckConstraint(
            "width_cm IS NULL OR width_cm > 0",
            name=op.f("ck_containers_container_width_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["households.id"],
            name=op.f("fk_containers_household_id_households"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_containers")),
        sa.UniqueConstraint(
            "household_id", "container_code", name="container_code_per_household"
        ),
    )
    with op.batch_alter_table("containers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_containers_household_id"), ["household_id"], unique=False
        )

    op.create_table(
        "plant_container_history",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("container_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ROOT_CONTAINER",
                "OUTER_CACHEPOT",
                "RESERVOIR",
                "MOUNT",
                "SUPPORT",
                "OTHER",
                name="plant_container_role",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name=op.f("ck_plant_container_history_plant_container_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["container_id"],
            ["containers.id"],
            name=op.f("fk_plant_container_history_container_id_containers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_container_history_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_container_history")),
        sa.UniqueConstraint(
            "plant_id", "container_id", "started_at", name="plant_container_start"
        ),
    )
    with op.batch_alter_table("plant_container_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_container_history_container_id"),
            ["container_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_container_history_plant_id"),
            ["plant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_container_history_started_at"),
            ["started_at"],
            unique=False,
        )

    op.create_table(
        "plant_cultivation_history",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method_type",
            sa.Enum(
                "SOIL_BASED",
                "SOILLESS_MIX",
                "ORCHID_BARK",
                "SPHAGNUM_MOSS",
                "SEMI_HYDRO_LECA",
                "SEMI_HYDRO_PON",
                "FULL_WATER_CULTURE",
                "WATER_PROPAGATION",
                "MOUNTED",
                "BARE_ROOT_AIR",
                "OTHER",
                name="growing_method_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("custom_method_name", sa.String(length=150), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "root_submersion_percent", sa.Numeric(precision=5, scale=2), nullable=True
        ),
        sa.Column(
            "reservoir_target_depth_cm", sa.Numeric(precision=6, scale=2), nullable=True
        ),
        sa.Column("is_experimental", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name=op.f("ck_plant_cultivation_history_plant_cultivation_end_after_start"),
        ),
        sa.CheckConstraint(
            "reservoir_target_depth_cm IS NULL OR reservoir_target_depth_cm >= 0",
            name=op.f(
                "ck_plant_cultivation_history_plant_cultivation_reservoir_depth_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "root_submersion_percent IS NULL OR root_submersion_percent BETWEEN 0 AND 100",
            name=op.f(
                "ck_plant_cultivation_history_plant_cultivation_root_submersion_range"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_cultivation_history_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_cultivation_history")),
        sa.UniqueConstraint(
            "plant_id", "started_at", name="plant_cultivation_start_per_plant"
        ),
    )
    with op.batch_alter_table("plant_cultivation_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_cultivation_history_plant_id"),
            ["plant_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_cultivation_history_started_at"),
            ["started_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plant_cultivation_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_cultivation_history_started_at"))
        batch_op.drop_index(batch_op.f("ix_plant_cultivation_history_plant_id"))

    op.drop_table("plant_cultivation_history")
    with op.batch_alter_table("plant_container_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_container_history_started_at"))
        batch_op.drop_index(batch_op.f("ix_plant_container_history_plant_id"))
        batch_op.drop_index(batch_op.f("ix_plant_container_history_container_id"))

    op.drop_table("plant_container_history")
    with op.batch_alter_table("containers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_containers_household_id"))

    op.drop_table("containers")
    # ### end Alembic commands ###
