"""Create initial database schema

Revision ID: 8b523f53c857
Revises:
Create Date: 2026-09-04 00:07:17.270934

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8b523f53c857'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_households'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('household_memberships',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'CARETAKER', 'MEMBER', name='household_role', native_enum=False), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_household_memberships_household_id_households'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_household_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household_memberships')),
    sa.UniqueConstraint('household_id', 'user_id', name='household_membership_once')
    )
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_household_memberships_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_household_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('sites',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('site_type', sa.Enum('HOUSE', 'APARTMENT', 'GREENHOUSE', 'OFFICE', 'OTHER', name='site_type', native_enum=False), nullable=False),
    sa.Column('address_text', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('elevation_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('terrain_position', sa.Enum('VALLEY', 'FLAT', 'SLOPE', 'HILLTOP', 'UNKNOWN', name='terrain_position', native_enum=False), nullable=False),
    sa.Column('terrain_slope_degrees', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('weather_enabled', sa.Boolean(), nullable=False),
    sa.Column('weather_provider', sa.String(length=50), nullable=False),
    sa.Column('weather_sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('elevation_m IS NULL OR elevation_m BETWEEN -500 AND 9000', name=op.f('ck_sites_valid_elevation')),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90 AND 90', name=op.f('ck_sites_valid_latitude')),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180 AND 180', name=op.f('ck_sites_valid_longitude')),
    sa.CheckConstraint('terrain_slope_degrees IS NULL OR terrain_slope_degrees BETWEEN 0 AND 90', name=op.f('ck_sites_valid_terrain_slope')),
    sa.CheckConstraint('weather_sync_interval_minutes >= 15', name=op.f('ck_sites_valid_weather_sync_interval')),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], name=op.f('fk_sites_household_id_households'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites'))
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_household_id'), ['household_id'], unique=False)

    op.create_table('spaces',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('parent_space_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('space_type', sa.Enum('ROOM', 'BASEMENT', 'SUNROOM', 'GREENHOUSE', 'BALCONY', 'PATIO', 'PORCH', 'GROW_TENT', 'SHELF', 'OUTDOOR_BED', 'OTHER', name='space_type', native_enum=False), nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('height_above_ground_m', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('below_grade_fraction_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('below_grade_fraction_pct IS NULL OR below_grade_fraction_pct BETWEEN 0 AND 100', name=op.f('ck_spaces_valid_below_grade_fraction')),
    sa.CheckConstraint('height_above_ground_m IS NULL OR height_above_ground_m BETWEEN -20 AND 1000', name=op.f('ck_spaces_valid_height_above_ground')),
    sa.ForeignKeyConstraint(['parent_space_id'], ['spaces.id'], name=op.f('fk_spaces_parent_space_id_spaces'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_spaces_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces'))
    )
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_parent_space_id'), ['parent_space_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spaces_site_id'), ['site_id'], unique=False)

    op.create_table('environmental_zones',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone_type', sa.Enum('WINDOWSILL', 'TABLE', 'SHELF', 'PLANT_STAND', 'FLOOR', 'HANGING', 'BENCH', 'ROOM_CENTER', 'OUTDOOR', 'OTHER', name='zone_type', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('height_above_floor_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('direct_sun_possible', sa.Boolean(), nullable=True),
    sa.Column('obstruction_level', sa.Enum('NONE', 'LOW', 'MODERATE', 'HIGH', 'UNKNOWN', name='obstruction_level', native_enum=False), nullable=False),
    sa.Column('estimated_sky_view_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('estimated_sky_view_pct IS NULL OR estimated_sky_view_pct BETWEEN 0 AND 100', name=op.f('ck_environmental_zones_zone_sky_view_range')),
    sa.CheckConstraint('height_above_floor_m IS NULL OR height_above_floor_m >= 0', name=op.f('ck_environmental_zones_zone_height_above_floor_nonnegative')),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_environmental_zones_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environmental_zones')),
    sa.UniqueConstraint('space_id', 'name', name='zone_name_per_space')
    )
    with op.batch_alter_table('environmental_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environmental_zones_space_id'), ['space_id'], unique=False)

    op.create_table('light_sources',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.Enum('WINDOW', 'SKYLIGHT', 'GLASS_DOOR', 'GROW_LIGHT', 'OTHER', name='light_source_type', native_enum=False), nullable=False),
    sa.Column('orientation_degrees', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('orientation_source', sa.Enum('ESTIMATED', 'PHONE_COMPASS', 'MEASURED', 'ROOM_SCAN', 'UNKNOWN', name='orientation_source', native_enum=False), nullable=False),
    sa.Column('orientation_accuracy_degrees', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('width_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sill_height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('transmission_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('wattage_w', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('color_temperature_k', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('color_temperature_k IS NULL OR color_temperature_k > 0', name=op.f('ck_light_sources_light_source_color_temperature_positive')),
    sa.CheckConstraint('height_m IS NULL OR height_m > 0', name=op.f('ck_light_sources_light_source_height_positive')),
    sa.CheckConstraint('orientation_accuracy_degrees IS NULL OR orientation_accuracy_degrees >= 0', name=op.f('ck_light_sources_light_source_orientation_accuracy_nonnegative')),
    sa.CheckConstraint('orientation_degrees IS NULL OR (orientation_degrees >= 0 AND orientation_degrees < 360)', name=op.f('ck_light_sources_light_source_orientation_range')),
    sa.CheckConstraint('sill_height_m IS NULL OR sill_height_m >= 0', name=op.f('ck_light_sources_light_source_sill_height_nonnegative')),
    sa.CheckConstraint('transmission_percent IS NULL OR (transmission_percent >= 0 AND transmission_percent <= 100)', name=op.f('ck_light_sources_light_source_transmission_range')),
    sa.CheckConstraint('wattage_w IS NULL OR wattage_w >= 0', name=op.f('ck_light_sources_light_source_wattage_nonnegative')),
    sa.CheckConstraint('width_m IS NULL OR width_m > 0', name=op.f('ck_light_sources_light_source_width_positive')),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_light_sources_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_light_sources'))
    )
    with op.batch_alter_table('light_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_light_sources_space_id'), ['space_id'], unique=False)

    op.create_table('zone_light_sources',
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('light_source_id', sa.Uuid(), nullable=False),
    sa.Column('distance_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('has_clear_line_of_sight', sa.Boolean(), nullable=True),
    sa.Column('contribution_weight', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('contribution_weight IS NULL OR (contribution_weight >= 0 AND contribution_weight <= 1)', name=op.f('ck_zone_light_sources_zone_light_source_contribution_weight_range')),
    sa.CheckConstraint('distance_m IS NULL OR distance_m >= 0', name=op.f('ck_zone_light_sources_zone_light_source_distance_nonnegative')),
    sa.ForeignKeyConstraint(['light_source_id'], ['light_sources.id'], name=op.f('fk_zone_light_sources_light_source_id_light_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['environmental_zones.id'], name=op.f('fk_zone_light_sources_zone_id_environmental_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_light_sources')),
    sa.UniqueConstraint('zone_id', 'light_source_id', name='uq_zone_light_sources_zone_light_source')
    )
    with op.batch_alter_table('zone_light_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_light_sources_light_source_id'), ['light_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_light_sources_zone_id'), ['zone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_light_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_light_sources_zone_id'))
        batch_op.drop_index(batch_op.f('ix_zone_light_sources_light_source_id'))

    op.drop_table('zone_light_sources')
    with op.batch_alter_table('light_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_light_sources_space_id'))

    op.drop_table('light_sources')
    with op.batch_alter_table('environmental_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environmental_zones_space_id'))

    op.drop_table('environmental_zones')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_site_id'))
        batch_op.drop_index(batch_op.f('ix_spaces_parent_space_id'))

    op.drop_table('spaces')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_household_id'))

    op.drop_table('sites')
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_household_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_household_memberships_household_id'))

    op.drop_table('household_memberships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('households')
    # ### end Alembic commands ###
