"""Add plant lifecycle and location history

Revision ID: a28eea245a64
Revises: 2718d45a1228
Create Date: 2026-09-04 12:50:04.240837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a28eea245a64"
down_revision: str | Sequence[str] | None = "2718d45a1228"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plant_lifecycle_events",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ACQUIRED",
                "PROPAGATED",
                "STATUS_CHANGED",
                "DORMANCY_STARTED",
                "DORMANCY_ENDED",
                "QUARANTINED",
                "RECOVERED",
                "TRANSFERRED",
                "DECEASED",
                "OTHER",
                name="lifecycle_event_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status_after",
            sa.Enum(
                "ACTIVE",
                "DORMANT",
                "QUARANTINED",
                "DECEASED",
                "TRANSFERRED",
                "UNKNOWN",
                name="plant_status",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_lifecycle_events_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_lifecycle_events")),
    )
    with op.batch_alter_table("plant_lifecycle_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_lifecycle_events_occurred_at"),
            ["occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_lifecycle_events_plant_id"), ["plant_id"], unique=False
        )

    op.create_table(
        "plant_location_history",
        sa.Column("plant_id", sa.Uuid(), nullable=False),
        sa.Column("zone_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "reason",
            sa.Enum(
                "INITIAL_PLACEMENT",
                "LIGHT_ADJUSTMENT",
                "SEASONAL_MOVE",
                "QUARANTINE",
                "REPOTTING",
                "HOUSE_MOVE",
                "CARETAKER_TRANSFER",
                "OTHER",
                name="location_change_reason",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("placement_label", sa.String(length=200), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name=op.f("ck_plant_location_history_plant_location_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["plant_id"],
            ["plants.id"],
            name=op.f("fk_plant_location_history_plant_id_plants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["environmental_zones.id"],
            name=op.f("fk_plant_location_history_zone_id_environmental_zones"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plant_location_history")),
        sa.UniqueConstraint(
            "plant_id", "started_at", name="plant_location_start_per_plant"
        ),
    )
    with op.batch_alter_table("plant_location_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_plant_location_history_plant_id"), ["plant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_plant_location_history_started_at"),
            ["started_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_plant_location_history_zone_id"), ["zone_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plant_location_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_location_history_zone_id"))
        batch_op.drop_index(batch_op.f("ix_plant_location_history_started_at"))
        batch_op.drop_index(batch_op.f("ix_plant_location_history_plant_id"))

    op.drop_table("plant_location_history")
    with op.batch_alter_table("plant_lifecycle_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plant_lifecycle_events_plant_id"))
        batch_op.drop_index(batch_op.f("ix_plant_lifecycle_events_occurred_at"))

    op.drop_table("plant_lifecycle_events")
    # ### end Alembic commands ###
